version: "3.9"

services:
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis

  worker:
    build:
      context: ./worker
      dockerfile: ./dockerfile
    command:
      [
        "celery",
        "-A",
        "app.app_celery",
        "worker",
        "--loglevel=INFO",
        "--concurrency=2",
      ]
    environment:
      - BROKER_URL=redis://redis
      - RESULT_BACKEND=redis://redis
    depends_on:
      - redis
      - flower
    deploy:
      mode: replicated
      replicas: 2

  web:
    restart: always
    depends_on:
      - worker
      - flower
      - redis
    build:
      context: ./fast_api
      dockerfile: ./dockerfile
    volumes:
      - type: bind
        source: ./fast_api
        target: /opt/web
        volume:
          nocopy: true
    environment:
      - BROKER_URL=redis://redis
      - RESULT_BACKEND=redis://redis
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8000
